sudo: false
language: cpp

dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - qt5-qmake
      - g++-6
      - g++-7
      - g++-8

env:
  - QMAKE_CC=gcc-6 QMAKE_CXX=g++-6 QMAKESPEC=linux-g++
  - QMAKE_CC=gcc-7 QMAKE_CXX=g++-7 QMAKESPEC=linux-g++
  - QMAKE_CC=gcc-8 QMAKE_CXX=g++-8 QMAKESPEC=linux-g++
  - QMAKE_CC=clang-7.0 QMAKE_CXX=clang++-7.0 QMAKESPEC=linux-clang++

script:
  - qmake
  - make
